#!/bin/bash

if [ -n "$1" ]; then
	
	CONF_FILE=$1.mrec
	
	rm -f $CONF_FILE;
	touch $CONF_FILE;
	
	echo Creating $CONF_FILE file mapping all jack system ports
	
	INDEX=""
	
	echo "ports=(">> $CONF_FILE
	for CAPTURE in `jack_lsp -A | grep system:capture | sed -e 's/^[ \t]*//' -e 's/[ \t]*$//'`
	do
	
		if [ -n "$INDEX" ]; then
			echo "," >> $CONF_FILE
		fi
		
		INDEX=`echo $CAPTURE | awk -F"_" '{print $2}'`
		PLAYBACK=`jack_lsp -A | grep system:playback | grep $INDEX | head -1 | sed -e 's/^[ \t]*//' -e 's/[ \t]*$//'`
		
		echo -n \{ takes=\"\"\; record=\"rec\"\; mute=false\; thru=true\; connections=\[\"$CAPTURE\"\,\"$PLAYBACK\"\]\; name=\"\"\; \} >> $CONF_FILE
	
	done
	echo ""   >> $CONF_FILE
	echo ");" >> $CONF_FILE
	
	echo "version=1;" >> $CONF_FILE

	
else
	echo "Usage: meterec-init-conf <session-name>"
	exit 1
fi
